# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Flask
RUN pip install --trusted-host pypi.python.org Flask requests beautifulsoup4

# Expose port 5000 for the Flask app
EXPOSE 5000

# Specify the command to run the Flask app on container start
CMD ["python", "./flask_app.py"]

